export default {
  AF: {
    code: 'AF',
    dialCode: '93',
    name: 'Afghanistan (‫افغانستان‬‎)',
    priority: 0,
  },
  AL: {
    code: 'AL',
    dialCode: '355',
    name: 'Albania (Shqipëri)',
    priority: 0,
  },
  DZ: {
    code: 'DZ',
    dialCode: '213',
    name: 'Algeria (‫الجزائر‬‎)',
    priority: 0,
  },
  AS: {
    code: 'AS',
    dialCode: '1684',
    name: 'American Samoa',
    priority: 0,
  },
  AD: {
    code: 'AD',
    dialCode: '376',
    name: 'Andorra',
    priority: 0,
  },
  AO: {
    code: 'AO',
    dialCode: '244',
    name: 'Angola',
    priority: 0,
  },
  AI: {
    code: 'AI',
    dialCode: '1264',
    name: 'Anguilla',
    priority: 0,
  },
  AG: {
    code: 'AG',
    dialCode: '1268',
    name: 'Antigua and Barbuda',
    priority: 0,
  },
  AR: {
    code: 'AR',
    dialCode: '54',
    name: 'Argentina',
    priority: 0,
  },
  AM: {
    code: 'AM',
    dialCode: '374',
    name: 'Armenia (Հայաստան)',
    priority: 0,
  },
  AW: {
    code: 'AW',
    dialCode: '297',
    name: 'Aruba',
    priority: 0,
  },
  AU: {
    code: 'AU',
    dialCode: '61',
    name: 'Australia',
    priority: 0,
  },
  AT: {
    code: 'AT',
    dialCode: '43',
    name: 'Austria (Österreich)',
    priority: 0,
  },
  AZ: {
    code: 'AZ',
    dialCode: '994',
    name: 'Azerbaijan (Azərbaycan)',
    priority: 0,
  },
  BS: {
    code: 'BS',
    dialCode: '1242',
    name: 'Bahamas',
    priority: 0,
  },
  BH: {
    code: 'BH',
    dialCode: '973',
    name: 'Bahrain (‫البحرين‬‎)',
    priority: 0,
  },
  BD: {
    code: 'BD',
    dialCode: '880',
    name: 'Bangladesh (বাংলাদেশ)',
    priority: 0,
  },
  BB: {
    code: 'BB',
    dialCode: '1246',
    name: 'Barbados',
    priority: 0,
  },
  BY: {
    code: 'BY',
    dialCode: '375',
    name: 'Belarus (Беларусь)',
    priority: 0,
  },
  BE: {
    code: 'BE',
    dialCode: '32',
    name: 'Belgium (België)',
    priority: 0,
  },
  BZ: {
    code: 'BZ',
    dialCode: '501',
    name: 'Belize',
    priority: 0,
  },
  BJ: {
    code: 'BJ',
    dialCode: '229',
    name: 'Benin (Bénin)',
    priority: 0,
  },
  BM: {
    code: 'BM',
    dialCode: '1441',
    name: 'Bermuda',
    priority: 0,
  },
  BT: {
    code: 'BT',
    dialCode: '975',
    name: 'Bhutan (འབྲུག)',
    priority: 0,
  },
  BO: {
    code: 'BO',
    dialCode: '591',
    name: 'Bolivia',
    priority: 0,
  },
  BA: {
    code: 'BA',
    dialCode: '387',
    name: 'Bosnia and Herzegovina (Босна и Херцеговина)',
    priority: 0,
  },
  BW: {
    code: 'BW',
    dialCode: '267',
    name: 'Botswana',
    priority: 0,
  },
  BR: {
    code: 'BR',
    dialCode: '55',
    name: 'Brazil (Brasil)',
    priority: 0,
  },
  IO: {
    code: 'IO',
    dialCode: '246',
    name: 'British Indian Ocean Territory',
    priority: 0,
  },
  VG: {
    code: 'VG',
    dialCode: '1284',
    name: 'British Virgin Islands',
    priority: 0,
  },
  BN: {
    code: 'BN',
    dialCode: '673',
    name: 'Brunei',
    priority: 0,
  },
  BG: {
    code: 'BG',
    dialCode: '359',
    name: 'Bulgaria (България)',
    priority: 0,
  },
  BF: {
    code: 'BF',
    dialCode: '226',
    name: 'Burkina Faso',
    priority: 0,
  },
  BI: {
    code: 'BI',
    dialCode: '257',
    name: 'Burundi (Uburundi)',
    priority: 0,
  },
  KH: {
    code: 'KH',
    dialCode: '855',
    name: 'Cambodia (កម្ពុជា)',
    priority: 0,
  },
  CM: {
    code: 'CM',
    dialCode: '237',
    name: 'Cameroon (Cameroun)',
    priority: 0,
  },
  CA: {
    code: 'CA',
    dialCode: '1',
    name: 'Canada',
    priority: 1,
  },
  CV: {
    code: 'CV',
    dialCode: '238',
    name: 'Cape Verde (Kabu Verdi)',
    priority: 0,
  },
  BQ: {
    code: 'BQ',
    dialCode: '599',
    name: 'Caribbean Netherlands',
    priority: 1,
  },
  KY: {
    code: 'KY',
    dialCode: '1345',
    name: 'Cayman Islands',
    priority: 0,
  },
  CF: {
    code: 'CF',
    dialCode: '236',
    name: 'Central African Republic (République centrafricaine)',
    priority: 0,
  },
  TD: {
    code: 'TD',
    dialCode: '235',
    name: 'Chad (Tchad)',
    priority: 0,
  },
  CL: {
    code: 'CL',
    dialCode: '56',
    name: 'Chile',
    priority: 0,
  },
  CN: {
    code: 'CN',
    dialCode: '86',
    name: 'China (中国)',
    priority: 0,
  },
  CX: {
    code: 'CX',
    dialCode: '61',
    name: 'Christmas Island',
    priority: 2,
  },
  CC: {
    code: 'CC',
    dialCode: '61',
    name: 'Cocos (Keeling) Islands',
    priority: 1,
  },
  CO: {
    code: 'CO',
    dialCode: '57',
    name: 'Colombia',
    priority: 0,
  },
  KM: {
    code: 'KM',
    dialCode: '269',
    name: 'Comoros (‫جزر القمر‬‎)',
    priority: 0,
  },
  CD: {
    code: 'CD',
    dialCode: '243',
    name: 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)',
    priority: 0,
  },
  CG: {
    code: 'CG',
    dialCode: '242',
    name: 'Congo (Republic) (Congo-Brazzaville)',
    priority: 0,
  },
  CK: {
    code: 'CK',
    dialCode: '682',
    name: 'Cook Islands',
    priority: 0,
  },
  CR: {
    code: 'CR',
    dialCode: '506',
    name: 'Costa Rica',
    priority: 0,
  },
  CI: {
    code: 'CI',
    dialCode: '225',
    name: 'Côte d’Ivoire',
    priority: 0,
  },
  HR: {
    code: 'HR',
    dialCode: '385',
    name: 'Croatia (Hrvatska)',
    priority: 0,
  },
  CU: {
    code: 'CU',
    dialCode: '53',
    name: 'Cuba',
    priority: 0,
  },
  CW: {
    code: 'CW',
    dialCode: '599',
    name: 'Curaçao',
    priority: 0,
  },
  CY: {
    code: 'CY',
    dialCode: '357',
    name: 'Cyprus (Κύπρος)',
    priority: 0,
  },
  CZ: {
    code: 'CZ',
    dialCode: '420',
    name: 'Czech Republic (Česká republika)',
    priority: 0,
  },
  DK: {
    code: 'DK',
    dialCode: '45',
    name: 'Denmark (Danmark)',
    priority: 0,
  },
  DJ: {
    code: 'DJ',
    dialCode: '253',
    name: 'Djibouti',
    priority: 0,
  },
  DM: {
    code: 'DM',
    dialCode: '1767',
    name: 'Dominica',
    priority: 0,
  },
  DO: {
    code: 'DO',
    dialCode: '1',
    name: 'Dominican Republic (República Dominicana)',
    priority: 2,
  },
  EC: {
    code: 'EC',
    dialCode: '593',
    name: 'Ecuador',
    priority: 0,
  },
  EG: {
    code: 'EG',
    dialCode: '20',
    name: 'Egypt (‫مصر‬‎)',
    priority: 0,
  },
  SV: {
    code: 'SV',
    dialCode: '503',
    name: 'El Salvador',
    priority: 0,
  },
  GQ: {
    code: 'GQ',
    dialCode: '240',
    name: 'Equatorial Guinea (Guinea Ecuatorial)',
    priority: 0,
  },
  ER: {
    code: 'ER',
    dialCode: '291',
    name: 'Eritrea',
    priority: 0,
  },
  EE: {
    code: 'EE',
    dialCode: '372',
    name: 'Estonia (Eesti)',
    priority: 0,
  },
  ET: {
    code: 'ET',
    dialCode: '251',
    name: 'Ethiopia',
    priority: 0,
  },
  FK: {
    code: 'FK',
    dialCode: '500',
    name: 'Falkland Islands (Islas Malvinas)',
    priority: 0,
  },
  FO: {
    code: 'FO',
    dialCode: '298',
    name: 'Faroe Islands (Føroyar)',
    priority: 0,
  },
  FJ: {
    code: 'FJ',
    dialCode: '679',
    name: 'Fiji',
    priority: 0,
  },
  FI: {
    code: 'FI',
    dialCode: '358',
    name: 'Finland (Suomi)',
    priority: 0,
  },
  FR: {
    code: 'FR',
    dialCode: '33',
    name: 'France',
    priority: 0,
  },
  GF: {
    code: 'GF',
    dialCode: '594',
    name: 'French Guiana (Guyane française)',
    priority: 0,
  },
  PF: {
    code: 'PF',
    dialCode: '689',
    name: 'French Polynesia (Polynésie française)',
    priority: 0,
  },
  GA: {
    code: 'GA',
    dialCode: '241',
    name: 'Gabon',
    priority: 0,
  },
  GM: {
    code: 'GM',
    dialCode: '220',
    name: 'Gambia',
    priority: 0,
  },
  GE: {
    code: 'GE',
    dialCode: '995',
    name: 'Georgia (საქართველო)',
    priority: 0,
  },
  DE: {
    code: 'DE',
    dialCode: '49',
    name: 'Germany (Deutschland)',
    priority: 0,
  },
  GH: {
    code: 'GH',
    dialCode: '233',
    name: 'Ghana (Gaana)',
    priority: 0,
  },
  GI: {
    code: 'GI',
    dialCode: '350',
    name: 'Gibraltar',
    priority: 0,
  },
  GR: {
    code: 'GR',
    dialCode: '30',
    name: 'Greece (Ελλάδα)',
    priority: 0,
  },
  GL: {
    code: 'GL',
    dialCode: '299',
    name: 'Greenland (Kalaallit Nunaat)',
    priority: 0,
  },
  GD: {
    code: 'GD',
    dialCode: '1473',
    name: 'Grenada',
    priority: 0,
  },
  GP: {
    code: 'GP',
    dialCode: '590',
    name: 'Guadeloupe',
    priority: 0,
  },
  GU: {
    code: 'GU',
    dialCode: '1671',
    name: 'Guam',
    priority: 0,
  },
  GT: {
    code: 'GT',
    dialCode: '502',
    name: 'Guatemala',
    priority: 0,
  },
  GG: {
    code: 'GG',
    dialCode: '44',
    name: 'Guernsey',
    priority: 1,
  },
  GN: {
    code: 'GN',
    dialCode: '224',
    name: 'Guinea (Guinée)',
    priority: 0,
  },
  GW: {
    code: 'GW',
    dialCode: '245',
    name: 'Guinea-Bissau (Guiné Bissau)',
    priority: 0,
  },
  GY: {
    code: 'GY',
    dialCode: '592',
    name: 'Guyana',
    priority: 0,
  },
  HT: {
    code: 'HT',
    dialCode: '509',
    name: 'Haiti',
    priority: 0,
  },
  HN: {
    code: 'HN',
    dialCode: '504',
    name: 'Honduras',
    priority: 0,
  },
  HK: {
    code: 'HK',
    dialCode: '852',
    name: 'Hong Kong (香港)',
    priority: 0,
  },
  HU: {
    code: 'HU',
    dialCode: '36',
    name: 'Hungary (Magyarország)',
    priority: 0,
  },
  IS: {
    code: 'IS',
    dialCode: '354',
    name: 'Iceland (Ísland)',
    priority: 0,
  },
  IN: {
    code: 'IN',
    dialCode: '91',
    name: 'India (भारत)',
    priority: 0,
  },
  ID: {
    code: 'ID',
    dialCode: '62',
    name: 'Indonesia',
    priority: 0,
  },
  IR: {
    code: 'IR',
    dialCode: '98',
    name: 'Iran (‫ایران‬‎)',
    priority: 0,
  },
  IQ: {
    code: 'IQ',
    dialCode: '964',
    name: 'Iraq (‫العراق‬‎)',
    priority: 0,
  },
  IE: {
    code: 'IE',
    dialCode: '353',
    name: 'Ireland',
    priority: 0,
  },
  IM: {
    code: 'IM',
    dialCode: '44',
    name: 'Isle of Man',
    priority: 2,
  },
  IL: {
    code: 'IL',
    dialCode: '972',
    name: 'Israel (‫ישראל‬‎)',
    priority: 0,
  },
  IT: {
    code: 'IT',
    dialCode: '39',
    name: 'Italy (Italia)',
    priority: 0,
  },
  JM: {
    code: 'JM',
    dialCode: '1876',
    name: 'Jamaica',
    priority: 0,
  },
  JP: {
    code: 'JP',
    dialCode: '81',
    name: 'Japan (日本)',
    priority: 0,
  },
  JE: {
    code: 'JE',
    dialCode: '44',
    name: 'Jersey',
    priority: 3,
  },
  JO: {
    code: 'JO',
    dialCode: '962',
    name: 'Jordan (‫الأردن‬‎)',
    priority: 0,
  },
  KZ: {
    code: 'KZ',
    dialCode: '77',
    name: 'Kazakhstan (Казахстан)',
    priority: 1,
  },
  KE: {
    code: 'KE',
    dialCode: '254',
    name: 'Kenya',
    priority: 0,
  },
  KI: {
    code: 'KI',
    dialCode: '686',
    name: 'Kiribati',
    priority: 0,
  },
  KW: {
    code: 'KW',
    dialCode: '965',
    name: 'Kuwait (‫الكويت‬‎)',
    priority: 0,
  },
  KG: {
    code: 'KG',
    dialCode: '996',
    name: 'Kyrgyzstan (Кыргызстан)',
    priority: 0,
  },
  LA: {
    code: 'LA',
    dialCode: '856',
    name: 'Laos (ລາວ)',
    priority: 0,
  },
  LV: {
    code: 'LV',
    dialCode: '371',
    name: 'Latvia (Latvija)',
    priority: 0,
  },
  LB: {
    code: 'LB',
    dialCode: '961',
    name: 'Lebanon (‫لبنان‬‎)',
    priority: 0,
  },
  LS: {
    code: 'LS',
    dialCode: '266',
    name: 'Lesotho',
    priority: 0,
  },
  LR: {
    code: 'LR',
    dialCode: '231',
    name: 'Liberia',
    priority: 0,
  },
  LY: {
    code: 'LY',
    dialCode: '218',
    name: 'Libya (‫ليبيا‬‎)',
    priority: 0,
  },
  LI: {
    code: 'LI',
    dialCode: '423',
    name: 'Liechtenstein',
    priority: 0,
  },
  LT: {
    code: 'LT',
    dialCode: '370',
    name: 'Lithuania (Lietuva)',
    priority: 0,
  },
  LU: {
    code: 'LU',
    dialCode: '352',
    name: 'Luxembourg',
    priority: 0,
  },
  MO: {
    code: 'MO',
    dialCode: '853',
    name: 'Macau (澳門)',
    priority: 0,
  },
  MK: {
    code: 'MK',
    dialCode: '389',
    name: 'Macedonia (FYROM) (Македонија)',
    priority: 0,
  },
  MG: {
    code: 'MG',
    dialCode: '261',
    name: 'Madagascar (Madagasikara)',
    priority: 0,
  },
  MW: {
    code: 'MW',
    dialCode: '265',
    name: 'Malawi',
    priority: 0,
  },
  MY: {
    code: 'MY',
    dialCode: '60',
    name: 'Malaysia',
    priority: 0,
  },
  MV: {
    code: 'MV',
    dialCode: '960',
    name: 'Maldives',
    priority: 0,
  },
  ML: {
    code: 'ML',
    dialCode: '223',
    name: 'Mali',
    priority: 0,
  },
  MT: {
    code: 'MT',
    dialCode: '356',
    name: 'Malta',
    priority: 0,
  },
  MH: {
    code: 'MH',
    dialCode: '692',
    name: 'Marshall Islands',
    priority: 0,
  },
  MQ: {
    code: 'MQ',
    dialCode: '596',
    name: 'Martinique',
    priority: 0,
  },
  MR: {
    code: 'MR',
    dialCode: '222',
    name: 'Mauritania (‫موريتانيا‬‎)',
    priority: 0,
  },
  MU: {
    code: 'MU',
    dialCode: '230',
    name: 'Mauritius (Moris)',
    priority: 0,
  },
  YT: {
    code: 'YT',
    dialCode: '262',
    name: 'Mayotte',
    priority: 1,
  },
  MX: {
    code: 'MX',
    dialCode: '52',
    name: 'Mexico (México)',
    priority: 0,
  },
  FM: {
    code: 'FM',
    dialCode: '691',
    name: 'Micronesia',
    priority: 0,
  },
  MD: {
    code: 'MD',
    dialCode: '373',
    name: 'Moldova (Republica Moldova)',
    priority: 0,
  },
  MC: {
    code: 'MC',
    dialCode: '377',
    name: 'Monaco',
    priority: 0,
  },
  MN: {
    code: 'MN',
    dialCode: '976',
    name: 'Mongolia (Монгол)',
    priority: 0,
  },
  ME: {
    code: 'ME',
    dialCode: '382',
    name: 'Montenegro (Crna Gora)',
    priority: 0,
  },
  MS: {
    code: 'MS',
    dialCode: '1664',
    name: 'Montserrat',
    priority: 0,
  },
  MA: {
    code: 'MA',
    dialCode: '212',
    name: 'Morocco (‫المغرب‬‎)',
    priority: 0,
  },
  MZ: {
    code: 'MZ',
    dialCode: '258',
    name: 'Mozambique (Moçambique)',
    priority: 0,
  },
  MM: {
    code: 'MM',
    dialCode: '95',
    name: 'Myanmar (Burma)',
    priority: 0,
  },
  NA: {
    code: 'NA',
    dialCode: '264',
    name: 'Namibia (Namibië)',
    priority: 0,
  },
  NR: {
    code: 'NR',
    dialCode: '674',
    name: 'Nauru',
    priority: 0,
  },
  NP: {
    code: 'NP',
    dialCode: '977',
    name: 'Nepal (नेपाल)',
    priority: 0,
  },
  NL: {
    code: 'NL',
    dialCode: '31',
    name: 'Netherlands (Nederland)',
    priority: 0,
  },
  NC: {
    code: 'NC',
    dialCode: '687',
    name: 'New Caledonia (Nouvelle-Calédonie)',
    priority: 0,
  },
  NZ: {
    code: 'NZ',
    dialCode: '64',
    name: 'New Zealand',
    priority: 0,
  },
  NI: {
    code: 'NI',
    dialCode: '505',
    name: 'Nicaragua',
    priority: 0,
  },
  NE: {
    code: 'NE',
    dialCode: '227',
    name: 'Niger (Nijar)',
    priority: 0,
  },
  NG: {
    code: 'NG',
    dialCode: '234',
    name: 'Nigeria',
    priority: 0,
  },
  NU: {
    code: 'NU',
    dialCode: '683',
    name: 'Niue',
    priority: 0,
  },
  NF: {
    code: 'NF',
    dialCode: '672',
    name: 'Norfolk Island',
    priority: 0,
  },
  KP: {
    code: 'KP',
    dialCode: '850',
    name: 'North Korea (조선 민주주의 인민 공화국)',
    priority: 0,
  },
  MP: {
    code: 'MP',
    dialCode: '1670',
    name: 'Northern Mariana Islands',
    priority: 0,
  },
  NO: {
    code: 'NO',
    dialCode: '47',
    name: 'Norway (Norge)',
    priority: 0,
  },
  OM: {
    code: 'OM',
    dialCode: '968',
    name: 'Oman (‫عُمان‬‎)',
    priority: 0,
  },
  PK: {
    code: 'PK',
    dialCode: '92',
    name: 'Pakistan (‫پاکستان‬‎)',
    priority: 0,
  },
  PW: {
    code: 'PW',
    dialCode: '680',
    name: 'Palau',
    priority: 0,
  },
  PS: {
    code: 'PS',
    dialCode: '970',
    name: 'Palestine (‫فلسطين‬‎)',
    priority: 0,
  },
  PA: {
    code: 'PA',
    dialCode: '507',
    name: 'Panama (Panamá)',
    priority: 0,
  },
  PG: {
    code: 'PG',
    dialCode: '675',
    name: 'Papua New Guinea',
    priority: 0,
  },
  PY: {
    code: 'PY',
    dialCode: '595',
    name: 'Paraguay',
    priority: 0,
  },
  PE: {
    code: 'PE',
    dialCode: '51',
    name: 'Peru (Perú)',
    priority: 0,
  },
  PH: {
    code: 'PH',
    dialCode: '63',
    name: 'Philippines',
    priority: 0,
  },
  PL: {
    code: 'PL',
    dialCode: '48',
    name: 'Poland (Polska)',
    priority: 0,
  },
  PT: {
    code: 'PT',
    dialCode: '351',
    name: 'Portugal',
    priority: 0,
  },
  PR: {
    code: 'PR',
    dialCode: '1',
    name: 'Puerto Rico',
    priority: 3,
  },
  QA: {
    code: 'QA',
    dialCode: '974',
    name: 'Qatar (‫قطر‬‎)',
    priority: 0,
  },
  RE: {
    code: 'RE',
    dialCode: '262',
    name: 'Réunion (La Réunion)',
    priority: 0,
  },
  RO: {
    code: 'RO',
    dialCode: '40',
    name: 'Romania (România)',
    priority: 0,
  },
  RU: {
    code: 'RU',
    dialCode: '7',
    name: 'Russia (Россия)',
    priority: 0,
  },
  RW: {
    code: 'RW',
    dialCode: '250',
    name: 'Rwanda',
    priority: 0,
  },
  BL: {
    code: 'BL',
    dialCode: '590',
    name: 'Saint Barthélemy (Saint-Barthélemy)',
    priority: 1,
  },
  SH: {
    code: 'SH',
    dialCode: '290',
    name: 'Saint Helena',
    priority: 0,
  },
  KN: {
    code: 'KN',
    dialCode: '1869',
    name: 'Saint Kitts and Nevis',
    priority: 0,
  },
  LC: {
    code: 'LC',
    dialCode: '1758',
    name: 'Saint Lucia',
    priority: 0,
  },
  MF: {
    code: 'MF',
    dialCode: '590',
    name: 'Saint Martin (Saint-Martin (partie française))',
    priority: 2,
  },
  PM: {
    code: 'PM',
    dialCode: '508',
    name: 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)',
    priority: 0,
  },
  VC: {
    code: 'VC',
    dialCode: '1784',
    name: 'Saint Vincent and the Grenadines',
    priority: 0,
  },
  WS: {
    code: 'WS',
    dialCode: '685',
    name: 'Samoa',
    priority: 0,
  },
  SM: {
    code: 'SM',
    dialCode: '378',
    name: 'San Marino',
    priority: 0,
  },
  ST: {
    code: 'ST',
    dialCode: '239',
    name: 'São Tomé and Príncipe (São Tomé e Príncipe)',
    priority: 0,
  },
  SA: {
    code: 'SA',
    dialCode: '966',
    name: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)',
    priority: 0,
  },
  SN: {
    code: 'SN',
    dialCode: '221',
    name: 'Senegal (Sénégal)',
    priority: 0,
  },
  RS: {
    code: 'RS',
    dialCode: '381',
    name: 'Serbia (Србија)',
    priority: 0,
  },
  SC: {
    code: 'SC',
    dialCode: '248',
    name: 'Seychelles',
    priority: 0,
  },
  SL: {
    code: 'SL',
    dialCode: '232',
    name: 'Sierra Leone',
    priority: 0,
  },
  SG: {
    code: 'SG',
    dialCode: '65',
    name: 'Singapore',
    priority: 0,
  },
  SX: {
    code: 'SX',
    dialCode: '1721',
    name: 'Sint Maarten',
    priority: 0,
  },
  SK: {
    code: 'SK',
    dialCode: '421',
    name: 'Slovakia (Slovensko)',
    priority: 0,
  },
  SI: {
    code: 'SI',
    dialCode: '386',
    name: 'Slovenia (Slovenija)',
    priority: 0,
  },
  SB: {
    code: 'SB',
    dialCode: '677',
    name: 'Solomon Islands',
    priority: 0,
  },
  SO: {
    code: 'SO',
    dialCode: '252',
    name: 'Somalia (Soomaaliya)',
    priority: 0,
  },
  ZA: {
    code: 'ZA',
    dialCode: '27',
    name: 'South Africa',
    priority: 0,
  },
  KR: {
    code: 'KR',
    dialCode: '82',
    name: 'South Korea (대한민국)',
    priority: 0,
  },
  SS: {
    code: 'SS',
    dialCode: '211',
    name: 'South Sudan (‫جنوب السودان‬‎)',
    priority: 0,
  },
  ES: {
    code: 'ES',
    dialCode: '34',
    name: 'Spain (España)',
    priority: 0,
  },
  LK: {
    code: 'LK',
    dialCode: '94',
    name: 'Sri Lanka (ශ්‍රී ලංකාව)',
    priority: 0,
  },
  SD: {
    code: 'SD',
    dialCode: '249',
    name: 'Sudan (‫السودان‬‎)',
    priority: 0,
  },
  SR: {
    code: 'SR',
    dialCode: '597',
    name: 'Suriname',
    priority: 0,
  },
  SJ: {
    code: 'SJ',
    dialCode: '47',
    name: 'Svalbard and Jan Mayen',
    priority: 1,
  },
  SZ: {
    code: 'SZ',
    dialCode: '268',
    name: 'Swaziland',
    priority: 0,
  },
  SE: {
    code: 'SE',
    dialCode: '46',
    name: 'Sweden (Sverige)',
    priority: 0,
  },
  CH: {
    code: 'CH',
    dialCode: '41',
    name: 'Switzerland (Schweiz)',
    priority: 0,
  },
  SY: {
    code: 'SY',
    dialCode: '963',
    name: 'Syria (‫سوريا‬‎)',
    priority: 0,
  },
  TW: {
    code: 'TW',
    dialCode: '886',
    name: 'Taiwan (台灣)',
    priority: 0,
  },
  TJ: {
    code: 'TJ',
    dialCode: '992',
    name: 'Tajikistan',
    priority: 0,
  },
  TZ: {
    code: 'TZ',
    dialCode: '255',
    name: 'Tanzania',
    priority: 0,
  },
  TH: {
    code: 'TH',
    dialCode: '66',
    name: 'Thailand (ไทย)',
    priority: 0,
  },
  TL: {
    code: 'TL',
    dialCode: '670',
    name: 'Timor-Leste',
    priority: 0,
  },
  TG: {
    code: 'TG',
    dialCode: '228',
    name: 'Togo',
    priority: 0,
  },
  TK: {
    code: 'TK',
    dialCode: '690',
    name: 'Tokelau',
    priority: 0,
  },
  TO: {
    code: 'TO',
    dialCode: '676',
    name: 'Tonga',
    priority: 0,
  },
  TT: {
    code: 'TT',
    dialCode: '1868',
    name: 'Trinidad and Tobago',
    priority: 0,
  },
  TN: {
    code: 'TN',
    dialCode: '216',
    name: 'Tunisia (‫تونس‬‎)',
    priority: 0,
  },
  TR: {
    code: 'TR',
    dialCode: '90',
    name: 'Turkey (Türkiye)',
    priority: 0,
  },
  TM: {
    code: 'TM',
    dialCode: '993',
    name: 'Turkmenistan',
    priority: 0,
  },
  TC: {
    code: 'TC',
    dialCode: '1649',
    name: 'Turks and Caicos Islands',
    priority: 0,
  },
  TV: {
    code: 'TV',
    dialCode: '688',
    name: 'Tuvalu',
    priority: 0,
  },
  VI: {
    code: 'VI',
    dialCode: '1340',
    name: 'U.S. Virgin Islands',
    priority: 0,
  },
  UG: {
    code: 'UG',
    dialCode: '256',
    name: 'Uganda',
    priority: 0,
  },
  UA: {
    code: 'UA',
    dialCode: '380',
    name: 'Ukraine (Україна)',
    priority: 0,
  },
  AE: {
    code: 'AE',
    dialCode: '971',
    name: 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)',
    priority: 0,
  },
  GB: {
    code: 'GB',
    dialCode: '44',
    name: 'United Kingdom',
    priority: 0,
  },
  US: {
    code: 'US',
    dialCode: '1',
    name: 'United States',
    priority: 0,
  },
  UY: {
    code: 'UY',
    dialCode: '598',
    name: 'Uruguay',
    priority: 0,
  },
  UZ: {
    code: 'UZ',
    dialCode: '998',
    name: 'Uzbekistan (Oʻzbekiston)',
    priority: 0,
  },
  VU: {
    code: 'VU',
    dialCode: '678',
    name: 'Vanuatu',
    priority: 0,
  },
  VA: {
    code: 'VA',
    dialCode: '39',
    name: 'Vatican City (Città del Vaticano)',
    priority: 1,
  },
  VE: {
    code: 'VE',
    dialCode: '58',
    name: 'Venezuela',
    priority: 0,
  },
  VN: {
    code: 'VN',
    dialCode: '84',
    name: 'Vietnam (Việt Nam)',
    priority: 0,
  },
  WF: {
    code: 'WF',
    dialCode: '681',
    name: 'Wallis and Futuna',
    priority: 0,
  },
  EH: {
    code: 'EH',
    dialCode: '212',
    name: 'Western Sahara (‫الصحراء الغربية‬‎)',
    priority: 1,
  },
  YE: {
    code: 'YE',
    dialCode: '967',
    name: 'Yemen (‫اليمن‬‎)',
    priority: 0,
  },
  ZM: {
    code: 'ZM',
    dialCode: '260',
    name: 'Zambia',
    priority: 0,
  },
  ZW: {
    code: 'ZW',
    dialCode: '263',
    name: 'Zimbabwe',
    priority: 0,
  },
  AX: {
    code: 'AX',
    dialCode: '358',
    name: 'Åland Islands',
    priority: 1,
  },
} as const;
